version: "3"
services:
  web:
    image: vojtasvoboda/dingo-sandbox:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  imagecache:
    image: flyimg/flyimg-build
    ports:
      - "8010:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8020:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
