version: "3"
services:
  web:
    image: vojtasvoboda/dingo-sandbox:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
