version: "3"
services:
  web:
    image: vojtasvoboda/dingo-sandbox:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  imagecache:
    image: flyimg/flyimg-build
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
networks:
  webnet:
